model = "gpt-5.6-sol"
model_reasoning_effort = "xhigh"
model_supports_reasoning_summaries = true
approval_policy = "never"
sandbox_mode = "danger-full-access"
personality = "pragmatic"
service_tier = "fast"
plan_mode_reasoning_effort = "high"
mcp_oauth_credentials_store = "file"

notify = ["/Users/ping.xia/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[features]
hooks = true
multi_agent = true
goals = true
js_repl = false

[mcp_servers.atlassian]
url = "https://mcp.atlassian.com/v1/mcp"

[mcp_servers.datadog]
url = "https://mcp.datadoghq.com/api/unstable/mcp-server/mcp?toolsets=core,llmobs,ddsql,apm,kubernetes,synthetics"

[mcp_servers.datadog_staging]
url = "https://mcp.datad0g.com/api/unstable/mcp-server/mcp?toolsets=core,llmobs,ddsql,apm,kubernetes,synthetics"

[mcp_servers.node_repl]
args = []
command = "/Users/ping.xia/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node_repl"
startup_timeout_sec = 120

[mcp_servers.node_repl.env]
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = "/Users/ping.xia/Applications/ChatGPT.app/Contents/Resources/cua_node/lib/node_modules"
NODE_REPL_NODE_PATH = "/Users/ping.xia/Applications/ChatGPT.app/Contents/Resources/cua_node/bin/node"
NODE_REPL_TRUSTED_CODE_PATHS = "/Users/ping.xia/.codex"
CODEX_HOME = "/Users/ping.xia/.codex"
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "6d25aa7656feac858f3a3bdaea5bcbab0dbfd426c9de8e6931ce90c399ee8e4f,7abc8b22abade944bcd80135500416c7aee60c0e94290c7d644b54428a0013ab"
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
NODE_REPL_INSTRUCTIONS_USE_CASE_COMPUTER_USE = "Control desktop apps on macOS through Computer Use."
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
BROWSER_USE_CODEX_APP_VERSION = "26.707.91948"
CODEX_CLI_PATH = "/Users/ping.xia/Applications/ChatGPT.app/Contents/Resources/codex"

[mcp_servers.computer-use]
command = "./Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient"
args = ["mcp"]
cwd = "."
enabled = false

[tui]
theme = "catppuccin-macchiato"
alternate_screen = "never"
status_line = ["model-with-reasoning", "current-dir", "context-remaining"]
status_line_use_colors = true
terminal_title = ["activity", "project-name", "git-branch"]

[tui.model_availability_nux]
"gpt-5.5" = 4
"gpt-5.6-sol" = 4

[projects."/Users/ping.xia/dotfiles"]
trust_level = "trusted"

[projects."/Users/ping.xia/go/src/github.com/DataDog/dd-source"]
trust_level = "trusted"

[projects."/Users/ping.xia"]
trust_level = "trusted"

[projects."/Users/ping.xia/go/src/github.com/DataDog/dispatch_agents"]
trust_level = "trusted"

[projects."/Users/ping.xia/Documents"]
trust_level = "trusted"

[projects."/home/bits/go/src/github.com/DataDog/dd-source"]
trust_level = "trusted"

[projects."/Users/ping.xia/Documents/codex"]
trust_level = "trusted"

[projects."/home/bits/dotfiles"]
trust_level = "trusted"

[projects."/home/bits/go/src/github.com/DataDog/consul-config"]
trust_level = "trusted"

[projects."/Users/ping.xia/go/src/github.com/DataDog/code-gen-backend"]
trust_level = "trusted"

[projects."/home/bits"]
trust_level = "trusted"

[projects."/Users/ping.xia/Documents/py_playground"]
trust_level = "trusted"

[projects."/Users/ping.xia/Documents/pydantic-ai"]
trust_level = "trusted"

[marketplaces.openai-bundled]
last_updated = "2026-07-16T18:22:36Z"
source_type = "local"
source = "/Users/ping.xia/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-07-16T07:48:39Z"
source_type = "local"
source = "/Users/ping.xia/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."slack@openai-curated"]
enabled = true

[plugins."dd@datadog-claude-plugins"]
enabled = true

[plugins."sites@openai-bundled"]
enabled = false

[plugins."documents@openai-primary-runtime"]
enabled = false

[plugins."pdf@openai-primary-runtime"]
enabled = false

[plugins."spreadsheets@openai-primary-runtime"]
enabled = false

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."template-creator@openai-primary-runtime"]
enabled = false

[plugins."computer-use@openai-bundled"]
enabled = false

[plugins."visualize@openai-bundled"]
enabled = false

[plugins."browser@openai-bundled"]
enabled = false

[memories]
generate_memories = true
use_memories = true

[desktop]
followUpQueueMode = "queue"
dock-icon-preference = "codex-system"
codeFontSize = 14
sansFontSize = 16

[hooks.state]

[hooks.state."/Users/ping.xia/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:ac47a21a96720cb9d1473caa1dea1b58a7426c41e0568fcd18634b9307a232f1"

[hooks.state."/Users/ping.xia/.codex/hooks.json:stop:0:0"]
trusted_hash = "sha256:1d374ea956912e71bf3682f86a44c794c6aac8bde169b17222c4dfc71ca27b00"

[hooks.state."/Users/ping.xia/.codex/hooks.json:stop:1:0"]
trusted_hash = "sha256:5fcff6cbca89be762be16f81b898baeff0ad79746f20190bbbc6408b17b44352"

[hooks.state."dd@datadog-claude-plugins:hooks/hooks.json:session_start:0:0"]
trusted_hash = "sha256:a506e76ca69c4e69723a414d9251cf4b02db5b0432058c64ca3f6c8684786c73"

[hooks.state."dd@datadog-claude-plugins:hooks/hooks.json:user_prompt_submit:0:0"]
trusted_hash = "sha256:6a58e770acd72ebdd9038420c45d024a9b1478a89cc7145d5e1751792216b884"

[hooks.state."/home/bits/.codex/hooks.json:session_start:0:0"]
trusted_hash = "sha256:ac47a21a96720cb9d1473caa1dea1b58a7426c41e0568fcd18634b9307a232f1"

[hooks.state."/home/bits/.codex/hooks.json:stop:0:0"]
trusted_hash = "sha256:1d374ea956912e71bf3682f86a44c794c6aac8bde169b17222c4dfc71ca27b00"

[hooks.state."/home/bits/.codex/hooks.json:stop:1:0"]
trusted_hash = "sha256:5fcff6cbca89be762be16f81b898baeff0ad79746f20190bbbc6408b17b44352"

[apps.connector_20205bf7d4e99a89d7154bb849718324]
enabled = false
