model = "gpt-5.5"
model_reasoning_effort = "high"
model_supports_reasoning_summaries = true
approval_policy = "never"
sandbox_mode = "danger-full-access"
personality = "pragmatic"
service_tier = "fast"
plan_mode_reasoning_effort = "high"

notify = ["/Users/ping.xia/.codex/computer-use/Codex Computer Use.app/Contents/SharedSupport/SkyComputerUseClient.app/Contents/MacOS/SkyComputerUseClient", "turn-ended"]

[features]
hooks = true
multi_agent = true
goals = true

[mcp_servers.atlassian]
url = "https://mcp.atlassian.com/v1/mcp"

[mcp_servers.datadog]
url = "https://mcp.datadoghq.com/api/unstable/mcp-server/mcp?toolsets=core,llmobs,ddsql,apm,kubernetes,synthetics"

[mcp_servers.datadog_staging]
url = "https://mcp.datad0g.com/api/unstable/mcp-server/mcp?toolsets=core,llmobs,ddsql,apm,kubernetes,synthetics"

[tui]
theme = "catppuccin-macchiato"
alternate_screen = "never"
status_line = ["model-with-reasoning", "current-dir", "context-remaining"]
status_line_use_colors = true
terminal_title = ["activity", "project-name", "git-branch"]

[tui.model_availability_nux]
"gpt-5.5" = 4

[projects."/Users/ping.xia/dotfiles"]
trust_level = "trusted"

[projects."/Users/ping.xia/go/src/github.com/DataDog/dd-source"]
trust_level = "trusted"

[projects."/Users/ping.xia"]
trust_level = "trusted"

[projects."/Users/ping.xia/go/src/github.com/DataDog/dispatch_agents"]
trust_level = "trusted"

[projects."/Users/ping.xia/Documents"]
trust_level = "trusted"

[projects."/home/bits/go/src/github.com/DataDog/dd-source"]
trust_level = "trusted"

[projects."/Users/ping.xia/Documents/codex"]
trust_level = "trusted"

[projects."/home/bits/dotfiles"]
trust_level = "trusted"

[projects."/home/bits/go/src/github.com/DataDog/consul-config"]
trust_level = "trusted"

[marketplaces.openai-bundled]
last_updated = "2026-05-27T17:51:04Z"
source_type = "local"
source = "/Users/ping.xia/.codex/.tmp/bundled-marketplaces/openai-bundled"

[marketplaces.openai-primary-runtime]
last_updated = "2026-06-24T10:46:45Z"
source_type = "local"
source = "/Users/ping.xia/.cache/codex-runtimes/codex-primary-runtime/plugins/openai-primary-runtime"

[plugins."computer-use@openai-bundled"]
enabled = true

[plugins."slack@openai-curated"]
enabled = true

[plugins."dd@datadog-claude-plugins"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[plugins."documents@openai-primary-runtime"]
enabled = false

[plugins."pdf@openai-primary-runtime"]
enabled = false

[plugins."spreadsheets@openai-primary-runtime"]
enabled = false

[plugins."presentations@openai-primary-runtime"]
enabled = false

[plugins."template-creator@openai-primary-runtime"]
enabled = false

[memories]
generate_memories = true
use_memories = true

[hooks.state]

[hooks.state."/Users/ping.xia/.codex/hooks.json:stop:0:0"]
trusted_hash = "sha256:1d374ea956912e71bf3682f86a44c794c6aac8bde169b17222c4dfc71ca27b00"

[hooks.state."/Users/ping.xia/.codex/hooks.json:stop:1:0"]
enabled = true
trusted_hash = "sha256:58def438adcf11ccc3170429aee88a653ddf9dbbdcb23ab194d7f66b2cfa2050"

[hooks.state."/home/bits/.codex/hooks.json:stop:0:0"]
trusted_hash = "sha256:1d374ea956912e71bf3682f86a44c794c6aac8bde169b17222c4dfc71ca27b00"

[hooks.state."/home/bits/.codex/hooks.json:stop:1:0"]
trusted_hash = "sha256:58def438adcf11ccc3170429aee88a653ddf9dbbdcb23ab194d7f66b2cfa2050"

[hooks.state."dd@datadog-claude-plugins:hooks/hooks.json:session_start:0:0"]
trusted_hash = "sha256:a506e76ca69c4e69723a414d9251cf4b02db5b0432058c64ca3f6c8684786c73"

[hooks.state."dd@datadog-claude-plugins:hooks/hooks.json:user_prompt_submit:0:0"]
trusted_hash = "sha256:6a58e770acd72ebdd9038420c45d024a9b1478a89cc7145d5e1751792216b884"

[apps.connector_20205bf7d4e99a89d7154bb849718324]
enabled = false
